### ISSUE TITLE
Someone fix build instructions!

### ISSUE THREAD

**Issue by Kakashi-BH** [TDesktop-x64/tdesktop#103]
### Is your feature request related to a problem?

Impossible to build in Visual Studio with these instructions...

https://github.com/TDesktop-x64/tdesktop/blob/dev/docs/building-msvc_x64.md

This file appears the most updated... but these instructions have commands for linux and not work....
Some of libraries not compile on VS2019 anymore...

**Comment by c0re100** [comment]
> ### Is your feature request related to a problem?
> Impossible to build in Visual Studio with these instructions...
> 
> https://github.com/TDesktop-x64/tdesktop/blob/dev/docs/building-msvc_x64.md
> 
> This file appears the most updated... but these instructions have commands for linux and not work.... Some of libraries not compile on VS2019 anymore...

https://github.com/TDesktop-x64/tdesktop/blob/dev/docs/building-win-x64.md
check it out, [building-msvc_x64.md](https://github.com/TDesktop-x64/tdesktop/blob/dev/docs/building-msvc_x64.md) is not longer update.
Since 64Gram now using official build instructions.
Just replace git clone url to 64Gram repo url is ok.

**Comment by Kakashi-BH** [comment]
Thank's I'll try it!
