### ISSUE TITLE
[Feature Request] feature to remove dead proxies

### ISSUE THREAD

**Issue by rezazoom** [TDesktop-x64/tdesktop#14]
![image](https://user-images.githubusercontent.com/40963038/97094628-47f8e780-1663-11eb-955e-827e5be99467.png)
### Lots of dead proxies for proxy users
Everyone using public proxies would have this issue, the list is growing everyday and more proxies are getting unavailable.

I like to have a feature to:
- remove **not available** proxies by a button,
- or just simply making them multi-selectable with Ctrl button to have them removed from the list.

**Comment by c0re100** [comment]
In [2.7.2.1](https://github.com/TDesktop-x64/tdesktop/releases/tag/v2.7.2.1), 64Gram have implemented "Remove all proxies" option in proxy setting.
Since it's hard to determine proxy server is dead or not
e.g.: server have some downtime for maintenance, but it's not unavailable forever
so remove all is the only option :)
